{
 "title": "Nexus blobs and repos",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(nexus_repository_blobstores{job=\"nexus-exporter\"},instance)"
    }
   },
   {
    "name": "repository",
    "query": {
     "query": "label_values(nexus_repository_repositories,name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nexus_repository_blobstores{instance=~\"$instance\",type=~\"size\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nexus_repository_blobstores{instance=~\"$instance\",type=~\"count\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Selected repository $repository ",
   "type": "timeseries",
   "description": "Selected repository",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nexus_repository_repositories{instance=~\"$instance\",type=~\"size\",name=~\"$repository\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "blobstores size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nexus_repository_blobstores{instance=~\"$instance\",type=~\"size\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "blobstores count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nexus_repository_blobstores{instance=~\"$instance\",type=~\"count\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "repositories size (exclude build)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nexus_repository_repositories{instance=~\"$instance\",type=~\"size\",name!~\"build\", name=~\"$repository\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "repositories count  (exclude build)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nexus_repository_repositories{instance=~\"$instance\",type=~\"count\",name!~\"build\", name=~\"$repository\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "build size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nexus_repository_repositories{instance=~\"$instance\",type=~\"size\",name=~\"build\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "bulid count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nexus_repository_repositories{instance=~\"$instance\",type=~\"count\",name=~\"build\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}